import { Car } from "../view/utils/interfaces";

const carNames = [
    {
        brand: "Mazda",
        models: [
            "121",
            "2",
            "3",
            "323",
            "323 Combi",
            "323 Coupé",
            "323 F",
            "5",
            "6",
            "6 Combi",
            "626",
            "626 Combi",
            "B-Fighter",
            "B2500",
            "BT",
            "CX-3",
            "CX-5",
            "CX-7",
            "CX-9",
            "Demio",
            "MPV",
            "MX-3",
            "MX-5",
            "MX-6",
            "Premacy",
            "RX-7",
            "RX-8",
            "Xedox 6",
        ],
    },
    {
        brand: "Škoda",
        models: [
            "Favorit",
            "Felicia",
            "Citigo",
            "Fabia",
            "Fabia Combi",
            "Fabia Sedan",
            "Felicia Combi",
            "Octavia",
            "Octavia Combi",
            "Roomster",
            "Yeti",
            "Rapid",
            "Rapid Spaceback",
            "Superb",
            "Superb Combi",
        ],
    },
    {
        brand: "Ford",
        models: [
            "Aerostar",
            "B-Max",
            "C-Max",
            "Cortina",
            "Cougar",
            "Edge",
            "Escort",
            "Escort Cabrio",
            "Escort kombi",
            "Explorer",
            "F-150",
            "F-250",
            "Fiesta",
            "Focus",
            "Focus C-Max",
            "Focus CC",
            "Focus kombi",
            "Fusion",
            "Galaxy",
            "Grand C-Max",
            "Ka",
            "Kuga",
            "Maverick",
            "Mondeo",
            "Mondeo Combi",
            "Mustang",
            "Orion",
            "Puma",
            "Ranger",
            "S-Max",
            "Sierra",
            "Street Ka",
            "Tourneo Connect",
            "Tourneo Custom",
            "Transit",
            "Transit",
            "Transit Bus",
            "Transit Connect LWB",
            "Transit Courier",
            "Transit Custom",
            "Transit kombi",
            "Transit Tourneo",
            "Transit Valnik",
            "Transit Van",
            "Transit Van 350",
            "Windstar",
        ],
    },
    {
        brand: "Renault",
        models: [
            "Captur",
            "Clio",
            "Clio Grandtour",
            "Espace",
            "Express",
            "Fluence",
            "Grand Espace",
            "Grand Modus",
            "Grand Scenic",
            "Kadjar",
            "Kangoo",
            "Kangoo Express",
            "Koleos",
            "Laguna",
            "Laguna Grandtour",
            "Latitude",
            "Mascott",
            "Mégane",
            "Mégane CC",
            "Mégane Combi",
            "Mégane Grandtour",
            "Mégane Coupé",
            "Mégane Scénic",
            "Scénic",
            "Talisman",
            "Talisman Grandtour",
            "Thalia",
            "Twingo",
            "Wind",
            "Zoé",
        ],
    },
    {
        brand: "Volvo",
        models: [
            "240",
            "340",
            "360",
            "460",
            "850",
            "850 kombi",
            "C30",
            "C70",
            "C70 Cabrio",
            "C70 Coupé",
            "S40",
            "S60",
            "S70",
            "S80",
            "S90",
            "V40",
            "V50",
            "V60",
            "V70",
            "V90",
            "XC60",
            "XC70",
            "XC90",
        ],
    },
    {
        brand: "Fiat",
        models: [
            "1100",
            "126",
            "500",
            "500L",
            "500X",
            "850",
            "Barchetta",
            "Brava",
            "Cinquecento",
            "Coupé",
            "Croma",
            "Doblo",
            "Doblo Cargo",
            "Doblo Cargo Combi",
            "Ducato",
            "Ducato Van",
            "Ducato Kombi",
            "Ducato Podvozok",
            "Florino",
            "Florino Combi",
            "Freemont",
            "Grande Punto",
            "Idea",
            "Linea",
            "Marea",
            "Marea Weekend",
            "Multipla",
            "Palio Weekend",
            "Panda",
            "Panda Van",
            "Punto",
            "Punto Cabriolet",
            "Punto Evo",
            "Punto Van",
            "Qubo",
            "Scudo",
            "Scudo Van",
            "Scudo Kombi",
            "Sedici",
            "Seicento",
            "Stilo",
            "Stilo Multiwagon",
            "Strada",
            "Talento",
            "Tipo",
            "Ulysse",
            "Uno",
            "X1/9",
        ],
    },
    {
        brand: "Porsche",
        models: [
            "911 Carrera",
            "911 Carrera Cabrio",
            "911 Targa",
            "911 Turbo",
            "924",
            "944",
            "997",
            "Boxster",
            "Cayenne",
            "Cayman",
            "Macan",
            "Panamera",
        ],
    },
    {
        brand: "Mercedes-Benz",
        models: [
            "100 D",
            "115",
            "124",
            "126",
            "190",
            "190 D",
            "190 E",
            "200 - 300",
            "200 D",
            "200 E",
            "210 Van",
            "210 kombi",
            "310 Van",
            "310 kombi",
            "230 - 300 CE Coupé",
            "260 - 560 SE",
            "260 - 560 SEL",
            "500 - 600 SEC Coupé",
            "Trieda A",
            "A",
            "A L",
            "AMG GT",
            "Trieda B",
            "Trieda C",
            "C",
            "C Sportcoupé",
            "C T",
            "Citan",
            "CL",
            "CL",
            "CLA",
            "CLC",
            "CLK Cabrio",
            "CLK Coupé",
            "CLS",
            "Trieda E",
            "E",
            "E Cabrio",
            "E Coupé",
            "E T",
            "Trieda G",
            "G Cabrio",
            "GL",
            "GLA",
            "GLC",
            "GLE",
            "GLK",
            "Trieda M",
            "MB 100",
            "Trieda R",
            "Trieda S",
            "S",
            "S Coupé",
            "SL",
            "SLC",
            "SLK",
            "SLR",
            "Sprinter",
        ],
    },
    {
        brand: "Toyota",
        models: [
            "4-Runner",
            "Auris",
            "Avensis",
            "Avensis Combi",
            "Avensis Van Verso",
            "Aygo",
            "Camry",
            "Carina",
            "Celica",
            "Corolla",
            "Corolla Combi",
            "Corolla sedan",
            "Corolla Verso",
            "FJ Cruiser",
            "GT86",
            "Hiace",
            "Hiace Van",
            "Highlander",
            "Hilux",
            "Land Cruiser",
            "MR2",
            "Paseo",
            "Picnic",
            "Prius",
            "RAV4",
            "Sequoia",
            "Starlet",
            "Supra",
            "Tundra",
            "Urban Cruiser",
            "Verso",
            "Yaris",
            "Yaris Verso",
        ],
    },
    {
        brand: "Seat",
        models: [
            "Alhambra",
            "Altea",
            "Altea XL",
            "Arosa",
            "Cordoba",
            "Cordoba Vario",
            "Exeo",
            "Ibiza",
            "Ibiza ST",
            "Exeo ST",
            "Leon",
            "Leon ST",
            "Inca",
            "Mii",
            "Toledo",
        ],
    },
];

function getRandomNumber(max: number): number {
    return Math.floor(Math.random() * max);
}

export function getRandomTitle(): string {
    const randomBrand = carNames[getRandomNumber(carNames.length)];
    const randomModel = randomBrand.models[getRandomNumber(randomBrand.models.length)];
    return randomBrand.brand.concat(" ", randomModel);
}

function getRandomColor(): string {
    const red = getRandomNumber(256).toString(16).padStart(2, "0");
    const green = getRandomNumber(256).toString(16).padStart(2, "0");
    const blue = getRandomNumber(256).toString(16).padStart(2, "0");
    return `#${red}${green}${blue}`;
}

export function getRandomCar(): Car {
    const name = getRandomTitle();
    const color = getRandomColor();
    return { name: name, color: color };
}
